#exercício 48
#crie um dicionário com todos os livros da bíblia e quantos capítulos cada um tem

biblia = {
    "genesis":50,
    "exodo": 40,
    "levitico": 27,
    "deuteronomio": 34,
    "josué": 24,
    "juizes" :21,
    "rute":4,
    "1samuel":31,
    "2samuel":34,
    "1reis":22,
    "2reis":25,
    "1cronicas":29,
    "2cronicas":36,
    "esdras":10,
    "neemias":13,
    "ester":10,
    "jó":42,
    "salmos":45,
    "provérbios":31,
    "eclesiastes":12,
    "cantares":12,
    "isaias":66,
    "jeremias":52,
    "lamentações":5,
    "ezequiel": 48,
    "daniel":12,
    "oseias":14,
    "joel":3,
    "amós":9,
    "obadias":1,
    "jonas":4,
    "miqueias":7,
    "naum":3,
    "habacuque":3,
    "sofonias":3,
    "ageu":2,
    "zacarias":14,
    "malaquias":4,
    "mateus":28,
    "marcos":16,
    "lucas":24,
    "joão":21,
    "atos":28,
    "romanos":16,
    "1corintios":16,
    "2corintios":13,
    "galatas":6,
    "efesios":6,
    "filipenses":4,
    "colossenses":6,
    "1tessalonicenses":5,
    "2tessaloniceneses":3,
    "1timoteo": 6,
    "2timoteo": 4,
    "tito":3,
    "filemon":1,
    "hebreus":13,
    "tiago":5,
    "1pedro":5,
    "2pedro":3,
    "1joao":5,
    "2joao":1,
    "3joão":1,
    "judas":1,
    "apocalipse":22
}

print(biblia["josué"])